---
title: "Assignment 3"
author: "Eva Juengling Bean"
format: pdf
editor: visual
---

```{r}
#| label: load-libraries
#| echo: true
#| warnings: false
#| message: false

rm(list=ls())

library(tidyverse)
library(janitor)
library(here)
library(ggplot2)
```

```{r}
#| label: make-data
#| echo: true
#| message: false
#| warnings: false

day <- seq(1,365, by=1)
pm25 <- runif(n=length(day), min=1, max=50)

data <- data.frame(day,pm25)
data$season <- as.factor(ifelse(data$day<=90, "winter", ifelse(data$day>270, "fall", ifelse(data$day>180, "summer", "spring"))))
data$risk <- NA
```

```{r}
#| label: looping
#| echo: true
#| warnings: false

good.thresh <- 12
mod.thresh <- 35.4
data$unhealthy.streak <- 0
max.unhealthy.streak <- 0

data$risk[1] <- ifelse(data$pm25[1]<=good.thresh, "good", ifelse(data$pm25>mod.thresh, "unhealthy", "moderate"))

for (i in 2:length(day)){
  if (data$pm25[i] <= good.thresh){
    data$risk[i]="good"
  } else if (data$pm25[i]<= mod.thresh){
    data$risk[i]="moderate"
  } else{
    data$risk[i]="unhealthy"
  }
  if (data$risk[i]=="unhealthy"){
    data$unhealthy.streak[i]=data$unhealthy.streak[i-1]+ifelse(data$risk[i]=="unhealthy",1,0)
  }
  max.unhealthy.streak=max(data$unhealthy.streak)
}

```


```{r}
#| label: season-summary
#| echo: true
#| warnings: false

winter.total <- 0
spring.total <- 0
summer.total <- 0
fall.total <- 0


for (i in 1:length(day)){
  if (data$season[i]=="winter" && data$risk[i]=="unhealthy"){
    winter.total = winter.total+1
  } else if (data$season[i]=="spring" && data$risk[i]=="unhealthy"){
    spring.total = spring.total+1
  } else if (data$season[i]=="summer"&& data$risk[i]=="unhealthy"){
    summer.total = summer.total+1
  } else if (data$risk[i]=="unhealthy"){
    fall.total = fall.total+1
  }
}

season.summary <- data.frame(winter.total, spring.total, summer.total, fall.total)
```

```{r}
#| label: plot
#| echo: true
#| warnings: false

pm25.trend.plot <- ggplot(data, aes(y=pm25, x=day, color=season))+
  geom_line()+
  theme_bw()

pm25.trend.plot

category.count <- ggplot(data, aes(x=risk))+
  geom_bar()+
  facet_wrap(data$season)+
  theme_bw()

category.count

```
